title: Min
author: Cycling '74
email: support@cycling74.com
description: > # this means to ignore newlines until "baseurl:"
  Code objects for Max in modern C++

twitter_username: cycling74
github_username:  cycling74

sass:
    style: compressed